// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ouwzqpcbvtthirgkqeji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91d3pxcGNidnR0aGlyZ2txZWppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MzE2NTUsImV4cCI6MjA2NjAwNzY1NX0.AtShHJUK8r_aTO0IU_8oCKDYj3IAtHpFidg9zAVLKm8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);